language: java

jdk: oraclejdk8

dist: trusty

addons:
  chrome: stable

before_script:
  - latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)
  - wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip -d /home/travis/build/
  - env webdriver.chrome.driver=/home/travis/build/

script:
  - mvn test -e -X
