language: java

services:
  - docker

jdk: oraclejdk8

dist: trusty

addons:
  apt:
    packages:
      - dpkg # this is required for fixing Travis' invalid chrome version issue
  chrome: stable

# env variables
# $RELEASE_BRANCH
# $GITHUB_TOKEN
# $ALLOWED_RELEASE_COMMITERS
# $SDK
git:
  submodules: false
before_install:
  - echo -e "\n\nmachine github.com\n  login $GITHUB_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive
before_script:
  - export SE_DOCKER="true" # TODO this is used with selenium-java 4.5.2 see PortProber.class L103 and may be subject to changed
  - export APPLITOOLS_REPORT_ID=${TRAVIS_COMMIT:0:7}-$TRAVIS_BUILD_NUMBER
  - echo "Travis tag is $TRAVIS_TAG"
  - echo "Travis event type is $TRAVIS_EVENT_TYPE"
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" || "$TRAVIS_TAG" =~ ^RELEASE_CANDIDATE ]]; then
    echo "Sandbox is false in test report";
    export APPLITOOLS_REPORT_TO_SANDBOX="false";
    echo "APPLITOOLS_REPORT_TO_SANDBOX=$APPLITOOLS_REPORT_TO_SANDBOX";
    fi
  - pushd eyes.ufg.java/src/main/resources
  - npm install
  - popd
  - mvn install -DskipTests
jobs:
  include:
    - name: Test chromedriver
      addons:
        apt:
          packages:
            - dpkg # this is required for fixing Travis' invalid chrome version issue
        chrome: stable
      if: type != cron
      script:
        - echo $APPLITOOLS_REPORT_ID
        - chmod +x ./initChromeDriver.sh && ./initChromeDriver.sh
        - export CHROME_DRIVER_PATH=/home/travis/build/chromedriver
        - chmod +x ./runTests.sh
#        - ./runTests.sh "eyes.selenium.java"