language: java

jdk: oraclejdk8

dist: trusty

addons:
  chrome: stable

jobs:
  include:
    - stage: before_test
      script:
        - latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)
        - wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
        - unzip chromedriver_linux64.zip -d /home/travis/build/
        - env webdriver.chrome.driver=/home/travis/build/
    - stage: replace_test_suite
      if: tag =~ ^RELEASE_CANDIDATE-
      script:
#       replace the devTestsSuite.xml testng xml with the stable regressionTestsSuite.xml
        - sed -i 's/devTestsSuite.xml/regressionTestsSuite.xml/g' $TRAVIS_BUILD_DIR/eyes.selenium.java/pom.xml
    - stage: test
      script:
        - cat $TRAVIS_BUILD_DIR/eyes.selenium.java/pom.xml
        - mvn test -e -X
    - stage: deploy
      if: tag =~ ^RELEASE_CANDIDATE- AND fork == false
      script:
#       save the email of the person who did the this commit in COMMITTER_EMAIL
        - COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - echo "DEPLOY"
#       run script to send mail report with two parametes: sdk and RELEASE_CANDIDATE-version tag
        - ./send_mail_report.sh java $TRAVIS_TAG
#        - if [[ $COMMITTER_EMAIL =~ $ALLOWED_COMMITERS ]]; then
#          echo "DEPLOY";
#          ./send_mail_report.sh java $TRAVIS_TAG;
#          fi