name: Web driver
description: Setup web driver (ChromeDriver/GeckoDriver)

inputs:
  chrome:
    description: should setup chrome driver
    type: boolean
    default: false
  chrome-version:
    description: chrome driver version
    type: string
  firefox:
    description: should setup gecko driver
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Install Chrome Driver
      if: ${{ inputs.chrome }}
      shell: bash
      run: |
        chromeVersion=`google-chrome --product-version | sed 's/\..*//'`
        echo "chrome version: $chromeVersion"
        latestChromeDriverVersion=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeVersion -q -O -)
        if [ ! -z "${{inputs.chrome-version}} ] 
        then
          latestChromeDriverVersion=${{inputs.chrome-version}}
        fi
        echo "chrome driver version: $latestChromeDriverVersion"
        wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverVersion}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
        /usr/local/bin/chromedriver --version
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &

    - name: Setup firefox
      if: ${{ inputs.firefox }}
      uses: browser-actions/setup-firefox@latest

    - name: Install Firefox Driver
      if: ${{ inputs.firefox }}
      shell: bash
      run: |
        wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz -P ~/
        tar -xzf ~/geckodriver-v0.29.1-linux64.tar.gz -C ~/
        rm ~/geckodriver-v0.29.1-linux64.tar.gz
        sudo mv -f ~/geckodriver /usr/local/bin/geckodriver
        sudo chmod +x /usr/local/bin/geckodriver
        
