name: Test on all platforms
on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ "8", "11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - run: |
          pushd eyes.ufg.java/src/main/resources
          npm install
          popd
          mvn install -DskipTests
          echo -e "\n\nmachine github.com\n  login $GH_TOKEN\n" >~/.netrc
          echo $APPLITOOLS_REPORT_ID
          chmod +x ./runTests.sh
          ./runTests.sh "eyes.sdk.core"
      
