name: Java - Setup (build and test)
on:
  workflow_call:
    inputs:
      build-config:
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - ${{ fromjson(inputs.build-config) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.SUBMODULES_GA_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - run: |
          echo "$MATRIX"
          echo $APPLITOOLS_REPORT_ID
          pushd eyes.ufg.java/src/main/resources
          npm install
          popd
          mvn install -DskipTests
        env:
          MATRIX: ${{ tojson(matrix) }}

  core-tests:
    needs: build
    strategy:
      matrix:
        include:
          - ${{ fromjson(inputs.build-config) }}
    runs-on: ${{ matrix.os }}
    setps:
      - run: |
          echo "Java SDK Core tests"
          chmod +x ./runTests.sh
          ./runTests.sh "eyes.sdk.core"