name: Java - Test on all platforms
on:
  push:
    branches:
      - bugfix_github_actions
#  pull_request:

jobs:
  core-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ "8", "11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.SUBMODULES_GA_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - name: initialize
        run: |
          pushd eyes.ufg.java/src/main/resources
          npm install
          popd
          mvn clean install -DskipTests
      - name: SDK Core tests
        run: |
          echo $APPLITOOLS_REPORT_ID
          mvn test -pl "eyes.sdk.core" -e -X
#          working-directory: java
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
